In [ ]:
#List practice
l1 = ['cat', 'dog', 'dang']
l2 = ['cats', 'dogs', 'dang sweater']
# l3 = l1.extend(l2) # CANNOT assign this way... 
l3 = l1
l3.extend(l2)
print(l3)

for item in l1:
    print(item)
for item in l2:
    print(item)
for item in l3:
   print(item)

In [ ]:
for i in range(len(l3)):
    print("Item", i, ":", l3[i])

l4 = l3
l4.append("ham")
print(l3, l4) # we can see that appending something by variable name l4 did not successfully create a new array... 

l5 = l3.copy()
l5.append("happy")
print(l3, l4, l5) # copy does work for allocating new memory to a variable 

for o in l3:
    o = "new " + o 
    l5.append(o)
print(l5)

In [ ]:
#list indexing / slicing

print(l5[::2])
print(l5[-1::-1])

l5.insert(2, "ample patience")
print(l5)
l5.remove("new ham")
print(l5)

In [ ]:
# Tuples: 

t1 = tuple(l5)
print(t1[2:10])
print(t1[2:-7])

someTerms = t1[:3]
(term1, term2, term3) = someTerms
print(term1,term2,term3)

s=''
for o in t1:
    s+=o
print(s.replace(' ', ''))

In [ ]:
# Dictionaries 

dict1 = {}
wordLen = [len(word) for word in l5]
print(wordLen)

for count, word in enumerate(l5):
    dict1[word] = wordLen[count]
print(dict1)
print(dict1.values())
print(dict1.keys())
print(dict1.items())

dict1.update({"new dogs" : "twenty seven"})
print(dict1)
dict1.update({"new Hand Type sound device" : "ffffffffffffffffffffffffffffffffffffffffffffff"})
print(dict1)

dict1.pop("ham")
print(dict1)

for k in dict1.keys():
    print(k)

In [ ]:
# Part 2 importing data 
import pandas as pd
import numpy as np

carsDF = pd.read_csv("./Data/cars.csv")
X = carsDF.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

#documentation suggests using .to_numpy() instead of .values() ... why though? 
X2 = carsDF.to_numpy()[:, 1:-1]
print(type(X2))
print(X2.shape)
print(X2)

In [ ]:
# subsetting
x1 = X2[0,:] # first row
x2 = X2[-1,:] # last row 
x12sum = x1+x2
print("sum", x12sum)

x3 = X2[:5,:] # first 5 
x4 = X2[-5:,:] # last 5 
x34sub = x3-x4
print("subtract", x34sub)


c1 = X2[:,0] # col 1
c2 = X2[:, -2] # 2nd to last col 
print("col1",c1)
print("co2",c2)

c12sub = c1-c2
c12sum = c1+c2
c12inner = np.inner(c1,c2)
c12mult = np.multiply(c1,c2)
print("col sub", c12sub)
print("col sum",c12sum)
print("col inner",c12inner)
print("col multiply",c12mult)

nrm1 = np.linalg.norm(c1, ord=1) 
nrm2 = np.linalg.norm(c1, ord=2) 
nrmINF = np.linalg.norm(c1, ord=np.inf) 
print("1 norm",nrm1)
print("1 norm",nrm2)
print("1 norm",nrmINF)

distC12 = np.linalg.norm(c1-c2, ord=2)
print("distance using 2-norm",distC12)

In [ ]:
# get first and last 3 cols 

A = X[:, :3]
print("A",A)
B = X[:,-3:]
print("B",B, "B shape", B.shape)

matSum = A+B
matSub = A-B
print("matSum\n",matSum, "\n", "matSub\n", matSub)

In [ ]:
#printSpace... limit... maybe find an option for the extension? 

C = np.transpose(B)
print(C.shape)

#AC = A*C # not sure if this is element wise multiplication... its not the dot product
AC = np.dot(A,C) 
print("shape AC:",AC.shape,"\n","AC:\n",AC)
#print(help(np))
T1 = np.full((3,3), 2)
T2 = np.full((3,3), 3)
print(T1*T2) # yeah its element wise multiplication 

In [21]:
D = np.transpose(A)
print("D shape:", D.shape)

DB = np.dot(D,B)
print("D:\n",D)


D shape: (3, 406)
D:
 [[18.0 15.0 18.0 ... 32.0 28.0 31.0]
 [8 8 8 ... 4 4 4]
 [307.0 350.0 318.0 ... 135.0 120.0 119.0]]
