In [ ]:
#List practice
l1 = ['cat', 'dog', 'dang']
l2 = ['cats', 'dogs', 'dang sweater']
# l3 = l1.extend(l2) # CANNOT assign this way... 
l3 = l1
l3.extend(l2)
print(l3)

for item in l1:
    print(item)
for item in l2:
    print(item)
for item in l3:
   print(item)

In [ ]:
for i in range(len(l3)):
    print("Item", i, ":", l3[i])

l4 = l3
l4.append("ham")
print(l3, l4) # we can see that appending something by variable name l4 did not successfully create a new array... 

l5 = l3.copy()
l5.append("happy")
print(l3, l4, l5) # copy does work for allocating new memory to a variable 

for o in l3:
    o = "new " + o 
    l5.append(o)
print(l5)

In [ ]:
#list indexing / slicing

print(l5[::2])
print(l5[-1::-1])

l5.insert(2, "ample patience")
print(l5)
l5.remove("new ham")
print(l5)

In [ ]:
# Tuples: 

t1 = tuple(l5)
print(t1[2:10])
print(t1[2:-7])

someTerms = t1[:3]
(term1, term2, term3) = someTerms
print(term1,term2,term3)

s=''
for o in t1:
    s+=o
print(s.replace(' ', ''))

In [ ]:
# Dictionaries 

dict1 = {}
wordLen = [len(word) for word in l5]
print(wordLen)

for count, word in enumerate(l5):
    dict1[word] = wordLen[count]
print(dict1)
print(dict1.values())
print(dict1.keys())
print(dict1.items())

dict1.update({"new dogs" : "twenty seven"})
print(dict1)
dict1.update({"new Hand Type sound device" : "ffffffffffffffffffffffffffffffffffffffffffffff"})
print(dict1)

dict1.pop("ham")
print(dict1)

for k in dict1.keys():
    print(k)

In [7]:
# Part 2
import pandas as pd
import numpy as np

carsDF = pd.read_csv("./Data/cars.csv")
X = carsDF.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)
#documentation suggests using .to_numpy() instead of .values()

X2 = carsDF.to_numpy()


<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]
